#!/usr/bin/env node
/*
 * Portions Copyright (c) 2017-2025 XMLmind Software. All rights reserved.
 * Author: Hussein Shafie
 *
 * Portions Copyright (c) 2026 Maxprograms SAS.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as
 * defined by the Mozilla Public License, v. 2.0.
 */

import { mkdirSync, rmSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
import { parseArgs } from "node:util";
import { Catalog, XMLDocument, XMLWriter } from "typesxml";
import { I18n } from "./i18n/I18n.js";
import { Chunking, chunkingFromString, joinChunkingStringForms } from "./preprocess/Chunking.js";
import { Filter } from "./preprocess/Filter.js";
import { LoadDocument } from "./preprocess/LoadDocument.js";
import { LoadedDocuments } from "./preprocess/LoadedDocuments.js";
import { ResourceHandler } from "./preprocess/ResourceHandler.js";
import { TypesDitacPreprocessor } from "./preprocess/TypesDitacPreprocessor.js";
import { DiagnosticLog } from "./utils/DiagnosticLog.js";

function usage(): void {
    console.log("\n" +
        "Usage:\n" +
        "  typesditac <map.ditamap> [options]\n" +
        "\n" +
        "Required:\n" +
        "  <map.ditamap>             DITA map to process\n" +
        "\n" +
        "Options:\n\n" +
        "  --output-dir <dir>        Where to write the output files\n" +
        "                            (default: <map-dir>/out/ditac/)\n" +
        "  --chunking <none|single|auto>\n" +
        "                            How to split the output into multiple files\n" +
        "                            (default: none); \"auto\" follows chunk hints in\n" +
        "                            the map itself\n" +
        "  --merge                   Write everything combined into a single,\n" +
        "                            self-contained XML file instead of the chunk\n" +
        "                            and list files\n" +
        "  -o, --output <file>       Where to write that combined file; only used\n" +
        "                            with --merge\n" +
        "                            (default: <output-dir>/<map-name>.xml)\n" +
        "  -v, --ditaval <file>      DITAVAL file (conditional filtering profile) to\n" +
        "                            apply\n" +
        "  -c, --catalog <file>      XML catalog to use while resolving referenced\n" +
        "                            files\n" +
        "  -l, --lang <lang>         Language for messages printed by this program\n" +
        "                            (default: system locale)\n" +
        "  --doc-lang <lang>         Default content language, used when the map\n" +
        "                            itself does not specify one\n" +
        "  --extract-images          Extract embedded SVG/MathML/LaTeX formulas as\n" +
        "                            separate image files instead of leaving them\n" +
        "                            inline\n" +
        "  --resources <dir>         Folder where referenced images and other non-XML\n" +
        "                            files are copied, relative to the output folder\n" +
        "                            (default: img)\n" +
        "  --media <screen|print>    Target medium, affects which content is\n" +
        "                            included/excluded (default: print)\n" +
        "  --toc                     Add a generated table of contents at the front\n" +
        "                            of the document\n" +
        "  --index                   Add a generated index at the back of the\n" +
        "                            document\n" +
        "  --frontmatter <spec>      Add other generated sections at the front; see\n" +
        "                            SECTION SPEC below\n" +
        "  --backmatter <spec>       Add other generated sections at the back; see\n" +
        "                            SECTION SPEC below\n" +
        "  -p, -param <name> <value> Specifies a conversion parameter: extended-toc\n" +
        "                            or title-page; see PARAMETERS below\n" +
        "  -h, --help                Show this help message\n" +
        "\n" +
        "PARAMETERS (for -p|-param <name> <value>):\n" +
        "  extended-toc              Which entries are listed in the table of\n" +
        "                            contents generated by --toc or a \"toc\" section\n" +
        "                            of --frontmatter/--backmatter, besides the body\n" +
        "                            entries (chapters, sections, etc.). Only used\n" +
        "                            with --merge. Values:\n" +
        "                              none         no other entries (default; any\n" +
        "                                           unrecognized value acts as\n" +
        "                                           none)\n" +
        "                              frontmatter  also the entries contained in\n" +
        "                                           <frontmatter>, listed before\n" +
        "                                           the body entries in a\n" +
        "                                           ditac:frontmatterTOC element\n" +
        "                              backmatter   also the entries contained in\n" +
        "                                           <backmatter>, such as the\n" +
        "                                           glossary and the index, listed\n" +
        "                                           after the body entries in a\n" +
        "                                           ditac:backmatterTOC element\n" +
        "                              both         frontmatter and backmatter\n" +
        "                                           entries\n" +
        "                            Entries of individual glossary items are never\n" +
        "                            listed.\n" +
        "  title-page                Controls the ditac:titlePage entry (title,\n" +
        "                            author, etc.). Values:\n" +
        "                              auto | none  the entry is generated only\n" +
        "                                           when the map has a title\n" +
        "                                           (default); rendering choices\n" +
        "                                           between them are left to the\n" +
        "                                           stylesheets, so they make no\n" +
        "                                           difference to this tool\n" +
        "                              other        URI of a custom title page:\n" +
        "                                           the entry is generated even if\n" +
        "                                           the map has no title\n" +
        "  Any other parameter name is rejected.\n" +
        "\n" +
        "SECTION SPEC (for --frontmatter/--backmatter):\n" +
        "  spec -> page [ ',' page ]*        one or more pages, separated by commas\n" +
        "  page -> section [ '+' section ]*  sections sharing one page, separated\n" +
        "                                    by '+'\n" +
        "  section -> toc|figurelist|tablelist|examplelist|equationlist|indexlist\n");
}

const FRONT_BACK_MATTER_SECTIONS: string[] = ["toc", "figurelist", "tablelist", "examplelist", "equationlist", "indexlist"];

function parseFrontBackMatter(spec: string): string[][] | undefined {
    const groups: string[][] = [];
    for (const samePage of spec.split(",")) {
        const sections: string[] = samePage.trim().split("+").map((section: string): string => section.trim());
        if (sections.some((section: string): boolean => !FRONT_BACK_MATTER_SECTIONS.includes(section))) {
            return undefined;
        }
        groups.push(sections);
    }
    return groups;
}

function systemLanguage(): string {
    const locale: string = Intl.DateTimeFormat().resolvedOptions().locale;
    const dashIndex: number = locale.indexOf("-");
    return dashIndex < 0 ? locale : locale.slice(0, dashIndex);
}

function extractParams(args: string[], params: Map<string, string>): string[] {
    const remaining: string[] = [];
    for (let index: number = 0; index < args.length; index++) {
        const arg: string = args[index];
        if (arg === "-p" || arg === "-param") {
            if (index + 2 >= args.length) {
                throw new Error("Option " + arg + " requires a parameter name and a value\n\n");
            }
            const name: string = args[index + 1];
            if (name !== "extended-toc" && name !== "title-page") {
                throw new Error("Unsupported parameter \"" + name + "\"; expected \"extended-toc\" or \"title-page\"\n\n");
            }
            params.set(name, args[index + 2]);
            index += 2;
        } else {
            remaining.push(arg);
        }
    }
    return remaining;
}

function runTypesDitac(): void {
    const params: Map<string, string> = new Map<string, string>();
    const { values, positionals } = parseArgs({
        args: extractParams(process.argv.slice(2), params),
        options: {
            output: { type: "string", short: "o" },
            ditaval: { type: "string", short: "v" },
            catalog: { type: "string", short: "c" },
            lang: { type: "string", short: "l" },
            "doc-lang": { type: "string" },
            "extract-images": { type: "boolean" },
            resources: { type: "string" },
            media: { type: "string" },
            chunking: { type: "string" },
            "output-dir": { type: "string" },
            merge: { type: "boolean" },
            toc: { type: "boolean" },
            index: { type: "boolean" },
            frontmatter: { type: "string" },
            backmatter: { type: "string" },
            help: { type: "boolean", short: "h" }
        },
        allowPositionals: true
    });

    if (values.help) {
        usage();
        return;
    }

    const missing: string[] = [];
    if (positionals.length === 0) {
        missing.push("<map.ditamap>");
    }
    if (missing.length > 0) {
        usage();
        return;
    }
    if (positionals.length > 1) {
        throw new Error("Only one DITAMAP file may be specified\n\n");
    }
    const mapPath: string = resolve(positionals[0]);
    const mapName: string = basename(mapPath, extname(mapPath));
    const outDir: string = values["output-dir"] === undefined
        ? resolve(dirname(mapPath), "out", "ditac")
        : resolve(values["output-dir"]);
    let outFile: string;
    if (values.merge === true) {
        outFile = values.output === undefined ? join(outDir, mapName + ".xml") : resolve(values.output);
    } else {
        outFile = join(outDir, mapName + TypesDitacPreprocessor.DITAC_SUFFIX);
    }
    mkdirSync(dirname(outFile), { recursive: true });

    const lang: string = values.lang ?? systemLanguage();
    const i18n: I18n = I18n.load(DiagnosticLog.I18N_DIRECTORY, "typesditac", lang);
    const diagnostics: DiagnosticLog = new DiagnosticLog(i18n);
    const catalogPath: string = values.catalog === undefined
        ? LoadDocument.DEFAULT_CATALOG
        : resolve(values.catalog);
    const catalog: Catalog = new Catalog(catalogPath);
    const documentLoader: LoadDocument = new LoadDocument(diagnostics, catalog);
    const documents: LoadedDocuments = new LoadedDocuments(documentLoader, diagnostics);
    const preprocessor: TypesDitacPreprocessor = new TypesDitacPreprocessor(documents, diagnostics);
    if (values["doc-lang"] !== undefined) {
        preprocessor.setLang(values["doc-lang"]);
    }
    const extendedToc: string | undefined = params.get("extended-toc");
    if (extendedToc !== undefined) {
        preprocessor.setExtendedToc(extendedToc);
    }
    const titlePage: string | undefined = params.get("title-page");
    if (titlePage !== undefined && titlePage !== "auto" && titlePage !== "none") {
        // A custom title page has been specified: force the generation of the title page
        preprocessor.setForceTitlePage(true);
    }
    if (values["extract-images"] === true) {
        preprocessor.setExtractAsImage(true);
    }
    preprocessor.setResourceHandler(new ResourceHandler(values.resources ?? "img", i18n));
    if (values.media !== undefined) {
        const spec: string = values.media.trim().toLowerCase();
        if (spec !== "screen" && spec !== "print") {
            throw new Error("Unknown media \"" + values.media + "\"; expected \"screen\" or \"print\"\n\n");
        }
        preprocessor.setMedia(spec);
    }
    if (values.chunking !== undefined) {
        const mode: Chunking | undefined = chunkingFromString(values.chunking);
        if (mode === undefined) {
            throw new Error("Unknown chunking mode \"" + values.chunking + "\"; expected " + joinChunkingStringForms("|") + "\n\n");
        }
        preprocessor.setChunking(mode);
    }
    if (values.toc === true) {
        preprocessor.setFrontMatter([["toc"]]);
    } else if (values.frontmatter !== undefined) {
        const items: string[][] | undefined = parseFrontBackMatter(values.frontmatter);
        if (items === undefined) {
            throw new Error("Invalid frontmatter spec \"" + values.frontmatter + "\"\n\n");
        }
        preprocessor.setFrontMatter(items);
    }
    if (values.index === true) {
        preprocessor.setBackMatter([["indexlist"]]);
    } else if (values.backmatter !== undefined) {
        const items: string[][] | undefined = parseFrontBackMatter(values.backmatter);
        if (items === undefined) {
            throw new Error("Invalid backmatter spec \"" + values.backmatter + "\"\n\n");
        }
        preprocessor.setBackMatter(items);
    }
    let filter: Filter | undefined;
    if (values.ditaval !== undefined) {
        filter = Filter.load(values.ditaval, documentLoader, i18n);
    }
    try {
        preprocessor.process(mapPath, outFile, filter);
        const written: { listsFile: string; chunkFiles: string[] } = preprocessor.writeChunkOutput();
        const unifiedDocument: XMLDocument | undefined = values.merge === true ? preprocessor.getUnifiedDocument() : undefined;
        if (unifiedDocument !== undefined) {
            XMLWriter.writeDocument(unifiedDocument, outFile);
            console.log("Merged XML document written to " + outFile);
            rmSync(join(preprocessor.getOutputDirectory(), TypesDitacPreprocessor.DITAC_SUBDIR_BASENAME), { recursive: true, force: true });
            rmSync(written.listsFile, { force: true });
            for (const chunkFile of written.chunkFiles) {
                rmSync(chunkFile, { force: true });
            }
        } else {
            console.log("Lists file written to " + written.listsFile);
            for (const chunkFile of written.chunkFiles) {
                console.log("Chunk file written to " + chunkFile);
            }
        }
    } catch (error: unknown) {
        diagnostics.fatal(error instanceof Error ? error.message : String(error));
        diagnostics.print((message: string): void => console.error(message));
        throw error;
    }
    diagnostics.print((message: string): void => console.error(message));
}

try {
    runTypesDitac();
} catch (error: unknown) {
    console.error("TypesDITA failed: " + (error instanceof Error ? error.message : error));
    process.exitCode = 1;
}
